"""
SOC Incident Generation (v1).

This module transforms explainable alerts produced by analyzer/risk_scoring.py into
structured SOC incident records ready for analyst triage.

Incident lifecycle statuses (design awareness for future database/SOC workflow):
- NEW            (assigned to all newly generated incidents in v1)
- ACKNOWLEDGED   (future stage)
- INVESTIGATING  (future stage)
- RESOLVED       (future stage)
- CLOSED         (future stage)

Scope & safety notes:
1. Incidents are generated ONLY when `alert["suspicious"] is True` and `alert["risk_score"] > 0`.
2. All investigation guidance is strictly non-destructive and advisory; no automated
   blocking, process termination, or firewall changes are performed.
3. Summary wording remains factual ("potentially suspicious DNS activity requiring
   investigation") and never claims confirmed DNS tunneling.
"""

from datetime import datetime, timezone
import json
from math import isfinite

try:
    from analyzer.detection_engine import calculate_baseline, detect_windows
    from analyzer.dns_aggregator import WINDOW_SIZE, aggregate_dns_records
    from analyzer.dns_reader import LOG_FILE, read_dns_log
    from analyzer.risk_scoring import (
        MAX_RISK_SCORE,
        MIN_RISK_SCORE,
        SEVERITY_CRITICAL,
        SEVERITY_HIGH,
        SEVERITY_LOW,
        SEVERITY_MEDIUM,
        get_severity,
        score_detections,
    )
except ImportError:
    from detection_engine import calculate_baseline, detect_windows
    from dns_aggregator import WINDOW_SIZE, aggregate_dns_records
    from dns_reader import LOG_FILE, read_dns_log
    from risk_scoring import (
        MAX_RISK_SCORE,
        MIN_RISK_SCORE,
        SEVERITY_CRITICAL,
        SEVERITY_HIGH,
        SEVERITY_LOW,
        SEVERITY_MEDIUM,
        get_severity,
        score_detections,
    )

# Incident lifecycle status constants
STATUS_NEW = "NEW"
STATUS_ACKNOWLEDGED = "ACKNOWLEDGED"
STATUS_INVESTIGATING = "INVESTIGATING"
STATUS_RESOLVED = "RESOLVED"
STATUS_CLOSED = "CLOSED"

VALID_INCIDENT_STATUSES = (
    STATUS_NEW,
    STATUS_ACKNOWLEDGED,
    STATUS_INVESTIGATING,
    STATUS_RESOLVED,
    STATUS_CLOSED,
)

VALID_INCIDENT_SEVERITIES = (
    SEVERITY_LOW,
    SEVERITY_MEDIUM,
    SEVERITY_HIGH,
    SEVERITY_CRITICAL,
)

INCIDENT_TITLE = "Potential DNS Tunneling Activity"
DEFAULT_INCIDENT_SUMMARY = (
    "Multiple correlated DNS behavioral indicators suggest potentially "
    "suspicious DNS activity requiring investigation."
)

DEFAULT_RECOMMENDED_ACTIONS: tuple[str, ...] = (
    "Review DNS queries generated by the source host.",
    "Investigate the queried domains and subdomains.",
    "Correlate the source IP with endpoint/network logs.",
    "Review the activity timeline around the detected window.",
    "Determine whether the behavior is expected for the source host.",
)


def _is_valid_number(value: object) -> bool:
    """Return True if value is a finite int or float (excluding booleans)."""
    return (
        isinstance(value, (int, float))
        and not isinstance(value, bool)
        and isfinite(value)
    )


def format_incident_id(
    sequence_number: int = 1,
    now: datetime | None = None,
) -> str:
    """
    Generate a human-readable incident identifier in the format INC-YYYYMMDD-NNNN.
    """
    if (
        not isinstance(sequence_number, int)
        or isinstance(sequence_number, bool)
        or sequence_number < 1
    ):
        raise ValueError("sequence_number must be a positive integer")

    timestamp = now if isinstance(now, datetime) else datetime.now(timezone.utc)
    date_part = timestamp.strftime("%Y%m%d")
    return f"INC-{date_part}-{sequence_number:04d}"


def is_qualifying_alert(alert: object) -> bool:
    """
    Validate that an alert object is well-formed and qualifies for incident generation.

    Requirements:
    - `alert` is a dict with `suspicious is True`
    - `risk_score` is a valid number in (0, 100]
    - `severity` is a valid non-NONE severity band matching `get_severity(risk_score)`
    - `source_ip` is a non-empty string
    - `window_start` and `window_end` are finite numbers with `window_end >= window_start`
    - `triggered_rules` is a non-empty list of strings
    - `score_breakdown` is a dict with valid numeric contributions
    - `evidence` is a list of dicts
    """
    if not isinstance(alert, dict):
        return False

    if alert.get("suspicious") is not True:
        return False

    risk_score = alert.get("risk_score")
    if (
        not _is_valid_number(risk_score)
        or risk_score <= MIN_RISK_SCORE
        or risk_score > MAX_RISK_SCORE
    ):
        return False

    severity = alert.get("severity")
    if (
        not isinstance(severity, str)
        or severity not in VALID_INCIDENT_SEVERITIES
        or severity != get_severity(risk_score)
    ):
        return False

    source_ip = alert.get("source_ip")
    if not isinstance(source_ip, str) or not source_ip.strip():
        return False

    window_start = alert.get("window_start")
    window_end = alert.get("window_end")
    if (
        not _is_valid_number(window_start)
        or not _is_valid_number(window_end)
        or window_end < window_start
    ):
        return False

    triggered_rules = alert.get("triggered_rules")
    if (
        not isinstance(triggered_rules, list)
        or not triggered_rules
        or not all(isinstance(r, str) and r.strip() for r in triggered_rules)
    ):
        return False

    score_breakdown = alert.get("score_breakdown")
    if not isinstance(score_breakdown, dict) or not score_breakdown:
        return False
    for k, v in score_breakdown.items():
        if not isinstance(k, str) or not _is_valid_number(v) or v <= 0:
            return False

    evidence = alert.get("evidence")
    if not isinstance(evidence, list) or not all(isinstance(e, dict) for e in evidence):
        return False

    return True


def _sanitize_summary(raw_summary: object) -> str:
    """Ensure the incident summary is factual and does not claim confirmed tunneling."""
    if not isinstance(raw_summary, str) or not raw_summary.strip():
        return DEFAULT_INCIDENT_SUMMARY

    cleaned = raw_summary.strip()
    if "confirmed" in cleaned.lower():
        return DEFAULT_INCIDENT_SUMMARY

    return cleaned


def generate_incident(
    alert: object,
    sequence_number: int = 1,
    now: datetime | None = None,
) -> dict | None:
    """
    Convert a single qualifying alert dictionary into a structured SOC incident.

    Returns None if the alert is non-suspicious, has risk_score <= 0, or is malformed.
    """
    if not is_qualifying_alert(alert):
        return None

    if (
        not isinstance(sequence_number, int)
        or isinstance(sequence_number, bool)
        or sequence_number < 1
    ):
        sequence_number = 1

    timestamp = now if isinstance(now, datetime) else datetime.now(timezone.utc)
    incident_id = format_incident_id(sequence_number=sequence_number, now=timestamp)

    assert isinstance(alert, dict)
    return {
        "incident_id": incident_id,
        "title": INCIDENT_TITLE,
        "source_ip": alert["source_ip"].strip(),
        "severity": alert["severity"],
        "risk_score": int(alert["risk_score"]),
        "status": STATUS_NEW,
        "created_at": timestamp.isoformat(),
        "window_start": alert["window_start"],
        "window_end": alert["window_end"],
        "triggered_rules": list(alert["triggered_rules"]),
        "score_breakdown": dict(alert["score_breakdown"]),
        "evidence": [dict(item) for item in alert["evidence"]],
        "summary": _sanitize_summary(alert.get("summary")),
        "investigation": {
            "recommended_actions": list(DEFAULT_RECOMMENDED_ACTIONS),
        },
    }


def generate_incidents(
    alerts: list[dict],
    start_sequence: int = 1,
    now: datetime | None = None,
) -> list[dict]:
    """
    Convert a list of alerts into structured SOC incidents, assigning sequential unique IDs.

    Non-suspicious or malformed alerts are skipped safely.
    """
    if not isinstance(alerts, list) or not alerts:
        return []

    seq = (
        start_sequence
        if isinstance(start_sequence, int)
        and not isinstance(start_sequence, bool)
        and start_sequence >= 1
        else 1
    )
    timestamp = now if isinstance(now, datetime) else datetime.now(timezone.utc)

    incidents: list[dict] = []
    for alert in alerts:
        incident = generate_incident(alert, sequence_number=seq, now=timestamp)
        if incident is not None:
            incidents.append(incident)
            seq += 1

    return incidents


def main() -> None:
    """Run the full pipeline through Incident Generation v1 on the normal dataset."""
    dns_records = read_dns_log(LOG_FILE)
    windows = aggregate_dns_records(dns_records, window_size=WINDOW_SIZE)
    baseline = calculate_baseline(windows)
    detections = detect_windows(windows, baseline)
    alerts = score_detections(detections)
    incidents = generate_incidents(alerts)

    suspicious_count = sum(1 for a in alerts if a["suspicious"])

    print("--- Incident Generator v1: Normal Dataset Report ---")
    print(f"Total Windows Evaluated: {len(alerts)}")
    print(f"Suspicious Windows: {suspicious_count}")
    print(f"Incidents Generated: {len(incidents)}")

    if incidents:
        print("\n--- Generated Incidents ---")
        for inc in incidents:
            print(json.dumps(inc, indent=4))


if __name__ == "__main__":
    main()
