"""
PostgreSQL repository for persisting and querying SOC DNS tunneling incidents.

Consumes the incident dictionaries generated by analyzer/incident_generator.py
without requiring changes to the upstream pipeline stages.
"""

from datetime import datetime
from math import isfinite

from psycopg2.extras import Json, RealDictCursor

try:
    from database.connection import db_connection, init_schema
except ImportError:
    from connection import db_connection, init_schema

REQUIRED_INCIDENT_FIELDS = (
    "incident_id",
    "title",
    "source_ip",
    "severity",
    "risk_score",
    "status",
    "created_at",
    "window_start",
    "window_end",
    "triggered_rules",
    "score_breakdown",
    "evidence",
    "summary",
    "investigation",
)


def _is_valid_number(value: object) -> bool:
    """Return True if value is a finite int or float (excluding booleans)."""
    return (
        isinstance(value, (int, float))
        and not isinstance(value, bool)
        and isfinite(value)
    )


def is_valid_incident(incident: object) -> bool:
    """Validate that an incident dictionary contains all required fields and valid types."""
    if not isinstance(incident, dict):
        return False

    for field in REQUIRED_INCIDENT_FIELDS:
        if field not in incident:
            return False

    for str_field in ("incident_id", "title", "source_ip", "severity", "status", "summary"):
        val = incident.get(str_field)
        if not isinstance(val, str) or not val.strip():
            return False

    created_at = incident.get("created_at")
    if not isinstance(created_at, (str, datetime)) or (
        isinstance(created_at, str) and not created_at.strip()
    ):
        return False

    risk_score = incident.get("risk_score")
    if not _is_valid_number(risk_score) or risk_score < 0 or risk_score > 100:
        return False

    window_start = incident.get("window_start")
    window_end = incident.get("window_end")
    if (
        not _is_valid_number(window_start)
        or not _is_valid_number(window_end)
        or window_end < window_start
    ):
        return False

    if not isinstance(incident.get("triggered_rules"), list):
        return False
    if not isinstance(incident.get("score_breakdown"), dict):
        return False
    if not isinstance(incident.get("evidence"), list):
        return False
    if not isinstance(incident.get("investigation"), dict):
        return False

    return True


def _row_to_incident_dict(row: dict) -> dict:
    """Convert a PostgreSQL RealDictRow into a standard incident dictionary."""
    created_at = row["created_at"]
    created_at_str = (
        created_at.isoformat()
        if hasattr(created_at, "isoformat")
        else str(created_at)
    )

    return {
        "id": int(row["id"]),
        "incident_id": row["incident_id"],
        "title": row["title"],
        "source_ip": row["source_ip"],
        "severity": row["severity"],
        "risk_score": int(row["risk_score"]),
        "status": row["status"],
        "created_at": created_at_str,
        "window_start": int(row["window_start"]),
        "window_end": int(row["window_end"]),
        "triggered_rules": row["triggered_rules"],
        "score_breakdown": row["score_breakdown"],
        "evidence": row["evidence"],
        "summary": row["summary"],
        "investigation": row["investigation"],
    }


def save_incident(incident: dict) -> bool:
    """
    Persist a single structured incident into PostgreSQL using parameterized SQL.

    Handles duplicate `incident_id` values safely via `ON CONFLICT (incident_id) DO NOTHING`:
    - Returns True if the incident was newly inserted.
    - Returns False if an incident with the same `incident_id` already exists.
    - Raises ValueError if the incident structure is invalid.
    """
    if not is_valid_incident(incident):
        raise ValueError("Invalid incident structure provided to save_incident().")

    insert_sql = """
        INSERT INTO incidents (
            incident_id,
            title,
            source_ip,
            severity,
            risk_score,
            status,
            created_at,
            window_start,
            window_end,
            triggered_rules,
            score_breakdown,
            evidence,
            summary,
            investigation
        )
        VALUES (
            %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s
        )
        ON CONFLICT (incident_id) DO NOTHING
        RETURNING id;
    """

    params = (
        incident["incident_id"].strip(),
        incident["title"].strip(),
        incident["source_ip"].strip(),
        incident["severity"].strip(),
        int(incident["risk_score"]),
        incident["status"].strip(),
        incident["created_at"],
        int(incident["window_start"]),
        int(incident["window_end"]),
        Json(incident["triggered_rules"]),
        Json(incident["score_breakdown"]),
        Json(incident["evidence"]),
        incident["summary"].strip(),
        Json(incident["investigation"]),
    )

    with db_connection() as conn:
        with conn.cursor() as cur:
            cur.execute(insert_sql, params)
            inserted = cur.fetchone() is not None

    return inserted


def save_incidents(incidents: list[dict]) -> int:
    """
    Persist a list of incidents and return the count of newly inserted records.
    """
    if not isinstance(incidents, list) or not incidents:
        return 0

    inserted_count = 0
    for incident in incidents:
        if save_incident(incident):
            inserted_count += 1
    return inserted_count


def get_incident_by_id(incident_id: str) -> dict | None:
    """
    Retrieve a single incident by its unique human-readable `incident_id`.

    Returns None if no matching incident exists or if `incident_id` is invalid.
    """
    if not isinstance(incident_id, str) or not incident_id.strip():
        return None

    select_sql = """
        SELECT
            id,
            incident_id,
            title,
            source_ip,
            severity,
            risk_score,
            status,
            created_at,
            window_start,
            window_end,
            triggered_rules,
            score_breakdown,
            evidence,
            summary,
            investigation
        FROM incidents
        WHERE incident_id = %s;
    """

    with db_connection() as conn:
        with conn.cursor(cursor_factory=RealDictCursor) as cur:
            cur.execute(select_sql, (incident_id.strip(),))
            row = cur.fetchone()

    if row is None:
        return None

    return _row_to_incident_dict(dict(row))


def get_all_incidents() -> list[dict]:
    """
    Retrieve all persisted incidents ordered chronologically by window_start and id.
    """
    select_all_sql = """
        SELECT
            id,
            incident_id,
            title,
            source_ip,
            severity,
            risk_score,
            status,
            created_at,
            window_start,
            window_end,
            triggered_rules,
            score_breakdown,
            evidence,
            summary,
            investigation
        FROM incidents
        ORDER BY window_start ASC, id ASC;
    """

    with db_connection() as conn:
        with conn.cursor(cursor_factory=RealDictCursor) as cur:
            cur.execute(select_all_sql)
            rows = cur.fetchall()

    return [_row_to_incident_dict(dict(r)) for r in rows]


def count_incidents() -> int:
    """Return the total number of incidents currently stored in the database."""
    count_sql = "SELECT COUNT(*) FROM incidents;"

    with db_connection() as conn:
        with conn.cursor() as cur:
            cur.execute(count_sql)
            row = cur.fetchone()

    return int(row[0]) if row is not None else 0


def clear_incidents() -> None:
    """Remove all rows from the incidents table (used for test isolation)."""
    with db_connection() as conn:
        with conn.cursor() as cur:
            cur.execute("TRUNCATE TABLE incidents RESTART IDENTITY;")


__all__ = [
    "clear_incidents",
    "count_incidents",
    "get_all_incidents",
    "get_incident_by_id",
    "init_schema",
    "is_valid_incident",
    "save_incident",
    "save_incidents",
]
